sudo: required
dist: trusty
language: ruby

cache:
  bundler: true

env:
  matrix:
    - JOB=BUILD
    - JOB=TEST
    - JOB=DANGER

rvm:
  - 2.3.3

install:
  - bundle install

script:
  - bash ./scripts/travis_build.sh

branches:
  only:
    - gh-pages
    - /./  # Allows builds for any other branch
